### ISSUE TITLE
[Ruby] Generated rubocop config should exclude ALL acceptance tests

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator#2186]
In the generated `.rubocop.yml` file, currently if there are acceptance tests, the exclusion rule lists only certain acceptance test files. For example, here is an excerpt from the generated file for speech:

```yaml
AllCops:
  Exclude:
    - "google-cloud-speech.gemspec"
    - "lib/google/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*smoke_test.rb"
```

Please instead exclude ALL files under the acceptance directory, in the same way that all files are excluded under the test directory. e.g.

```yaml
AllCops:
  Exclude:
    - "google-cloud-speech.gemspec"
    - "lib/google/**/*"
    - "Rakefile"
    - "test/**/*"
    - "acceptance/**/*"
```
