### ISSUE TITLE
cryptic null ptr error when `parameters.attributes.parameter` does not refer to an item listed in `parameters.defaults`

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/gapic-generator#2511]
In the `sample_value_sets` config, if `parameters.attributes.parameter` specifies a parameter not in `parameters.defaults`, then we get non-useful error message:

```
java.lang.NullPointerException
	at com.google.api.codegen.transformer.SurfaceNamer.getFieldSetFunctionName(SurfaceNamer.java:308)
```

This config segment seems to illustrate the problem:
```
      parameters:
        defaults:
        - document.content="Mary had a little lamb"
        - document.type=PLAIN_TEXT
        attributes:
        - parameter: document.gcs_content_uri
          sample_argument_name: foo
```
