### ISSUE TITLE
SampleGen: Attribute defined without default value does not raise error (only NullPointerException)

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2540]
Trying to generate a sample for Google Cloud Speech V1

The following works OK

```yaml
    samples:
      standalone:
      - calling_forms: ".*"
        value_sets: [speech_transcribe_sync]
        region_tag: speech_transcribe_sync
    sample_value_sets:
    - id: speech_transcribe_sync
      description: Transcribe local audio file
      parameters:
        defaults:
        - config.sample_rate_hertz=16000
        - config.language_code="en-US"
        - config.encoding=LINEAR16
        attributes:
        - parameter: config.language_code
          sample_argument_name: language_code
```

But if I try to add a binary field, I get the following:

```
WARNING: toplevel: (lint) control-presence: Service speech.googleapis.com does not have control environment configured.
ERROR: toplevel: Unexpected exception:
java.lang.NullPointerException
```

YAML:

```yaml
    samples:
      standalone:
      - calling_forms: ".*"
        value_sets: [speech_transcribe_sync]
        region_tag: speech_transcribe_sync
    sample_value_sets:
    - id: speech_transcribe_sync
      description: Transcribe local audio file
      parameters:
        defaults:
        - config.sample_rate_hertz=16000
        - config.language_code="en-US"
        - config.encoding=LINEAR16
        attributes:
        - parameter: config.language_code
          sample_argument_name: language_code
        - parameter: audio.content
          sample_argument_name: local_file_path
          read_file: true
```

To reproduce, generate Speech V1 using the attached YAML (note: for GitHub upload the file is named `speech_gapic.yaml.txt` – rename appropriately)

[speech_gapic.yaml.txt](https://github.com/googleapis/gapic-generator/files/2830138/speech_gapic.yaml.txt)
