### ISSUE TITLE
SampleGen: add attribute for parameter description

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2577]
I would like to update the snippets to look like this (_in the future – out of scope for this issue_ [`*`](https://github.com/beccasaurus/gapic-docs-samples/blob/master/code-samples/canonical-samples/python/synchronous-request/language_sentiment_text.py))

```py
# [START language_sentiment_text]
from google.cloud import language
from google.cloud.language import enums
from google.cloud.language import types

def analyze_sentiment_text(text_content='I am happy and joyful'):
    """Analyze sentiment of text
    Args:
        text: Text to analyze, e.g. 'Hello, world!'
    """

    client = language.LanguageServiceClient()

    document = types.Document(
        content=text_content,
        type=enums.Document.Type.PLAIN_TEXT)

    # ....
```

In this example, you'll notice a few things about this method parameter

 - (a) it's mapped to a request field _(**implemented!**)_
 - (b) it has a custom parameter name name _(**implemented!**)_
 - (c) it has a default value _(**implemented!**)_
 - (d) it has a docstring parameter description

I was thinking we could add this to the structural schema of samples:

```yaml
parameters:
  defaults:
  - document.type=PLAIN_TEXT
  - document.content="I am so happy and joyful."
  attributes:
  - parameter: document.content
    sample_argument_name: text_content
    description: "Text to analyze, e.g. 'Hello, world!'"  # <~~~ <~~~
```

`=>` @hzyi-google
