### ISSUE TITLE
SampleGen: `comment` adds extraneous comment newline

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2578]
My YAML:

```yaml
 on_success:
  - loop:
      variable: result
      collection: $resp.results
      body:
      - comment:
          - |
              First recognition hypothesis.
              These alternatives are ordered in terms of accuracy, with the top (first) alternative being the most probable.
      - comment:
          - "%s is the most probable recognition result."
          - first_alternative
      - define: first_alternative=result.alternatives[0]
# ...
```

My Python output:

```py
for result in response.results:
    # First recognition hypothesis.
    # These alternatives are ordered in terms of accuracy, with the top (first) alternative being the most probable.
    #
    # first_alternative is the most probable recognition result.
    first_alternative = result.alternatives[0]
```

The same is true in PHP:

```php
foreach ($response->getResults() as $result) {
    // First recognition hypothesis.
    // These alternatives are ordered in terms of accuracy, with the top (first) alternative being the most probable.
    //
    // firstAlternative is the most probable recognition result.
    $firstAlternative = $result->getAlternatives()[0];
```

As you can see, I needed a second `comment:` directive to make use of `%s` language-specific variable casing.

But I did not intend to add an empty comment line between the 2 `comment:` directives

=> @hzyi-google
