### ISSUE TITLE
SampleGen: cannot set default for named resource path including `.`

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2586]
Cannot generate a request for rpc with resource including `.`

e.g. `v1/`[`pubsub.proto`](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L49-L56) which has path `topic.name` (_many other APIs also use this pattern_)

```proto
// Updates an existing topic. Note that certain properties of a
// topic are not modifiable.
rpc UpdateTopic(UpdateTopicRequest) returns (Topic) {
  option (google.api.http) = {
    patch: "/v1/{topic.name=projects/*/topics/*}"    # <=== topic.name
    body: "*"
  };
}
```

Expected this to work:

```yaml
# Update Topic
#
# rpc UpdateTopic(UpdateTopicRequest) returns (Topic)
#   patch: "/v1/{topic.name=projects/*/topics/*}"
#
- name: UpdateTopic
  samples:
    standalone:
    - calling_forms: ".*"
      value_sets: [update_topic]
      region_tag: update_topic
  sample_value_sets:
  - id: update_topic
    parameters:
      defaults:
      - topic.name%project="Your Google Cloud Project ID"    # <== topic.name % {project}
      - topic.name%topic="Your Topic Name
```

Got this:

```
java.lang.IllegalArgumentException: The field name is not found in the collection map.
```

----

If you want to reproduce, try out this [`pubsub_gapic.yaml`](https://github.com/beccasaurus/gapic-docs-samples/blob/master/google/pubsub/v1/pubsub_gapic.yaml#L443-L515)

The rpc call for Creating a Topic works (the resource is simply `name`):

```proto
rpc CreateTopic(Topic) returns (Topic) {
  option (google.api.http) = {
    put: "/v1/{name=projects/*/topics/*}"
    body: "*"
  };
}
```

```yaml
- name: CreateTopic
  samples:
    standalone:
    - calling_forms: ".*"
      value_sets: [create_topic]
      region_tag: create_topic
  sample_value_sets:
  - id: create_topic
    parameters:
      defaults:
      - name%project="Your Google Cloud Project ID"
      - name%topic="Your Topic Name"
```

FYI here are the defined `collections`:

```yaml
collections:
- name_pattern: projects/{project}
  entity_name: project
  language_overrides:
  - language: csharp
    common_resource_name: Google.Api.Gax.ResourceNames.ProjectName
- name_pattern: projects/{project}/snapshots/{snapshot}
  entity_name: snapshot
  language_overrides:
  - language: java
    entity_name: project_snapshot
- name_pattern: projects/{project}/subscriptions/{subscription}
  entity_name: subscription
  language_overrides:
  - language: java
    entity_name: project_subscription
- name_pattern: projects/{project}/topics/{topic}
  entity_name: topic
  language_overrides:
  - language: java
    entity_name: project_topic
```

The `UpdateTopic` rpc uses `topic.name` and the pattern `projects/*/topics/*` – which is defined in `collections:` and uses variable names `{project}` and `{topic}`. I couldn't figure out if there's something other than `topic.name` that I should be using? I think I'm doing it right :)

=> @hzyi-google /cc @vchudnov-g
