### ISSUE TITLE
SampleGen: Node.js delete sample doesn't show response handling section

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2616]
Example:
 - [Sample definition](https://github.com/beccasaurus/gapic-docs-samples/blob/48ba35b04c9b915f5fb9bd4d9d2112db0875a601/google/cloud/talent/v4beta1/talent_gapic.yaml#L198-L216)
 - [Python sample](https://github.com/beccasaurus/gapic-docs-samples/blob/48ba35b04c9b915f5fb9bd4d9d2112db0875a601/code-samples/talent/v4beta1/python/delete_company_request_talent_delete_company.py#L46-L49) - OK
 - [PHP sample](https://github.com/beccasaurus/gapic-docs-samples/blob/48ba35b04c9b915f5fb9bd4d9d2112db0875a601/code-samples/talent/v4beta1/php/DeleteCompanyRequestTalentDeleteCompany.php#L37-L43) - OK _except there's a bug with the comment, take a look!_
 - [Java sample](https://github.com/beccasaurus/gapic-docs-samples/blob/48ba35b04c9b915f5fb9bd4d9d2112db0875a601/code-samples/talent/v4beta1/java/src/main/java/com/google/cloud/examples/talent/v4beta1/DeleteCompanyRequestTalentDeleteCompany.java#L30-L35) - OK
 - [Node.js sample](https://github.com/beccasaurus/gapic-docs-samples/blob/48ba35b04c9b915f5fb9bd4d9d2112db0875a601/code-samples/talent/v4beta1/nodejs/delete_company_request_talent_delete_company.js#L10-L18) - `<= the response body doesn't show up!!!`

#### Sample Definition

```yaml
- id: talent_delete_company
  description: Delete Company
  parameters:
    defaults:
    - name%project="Your Google Cloud Project ID CHANGED"
    - name%company="ID of the company to delete"
    attributes:
    - parameter: name%project
      sample_argument_name: project_id_changed
    - parameter: name%company
      sample_argument_name: company_id_changed
  on_success:
  - comment:
    - "What is going on?"
  - print:
    - "Hello???"
  - print:
    - "Deleted company"
```

#### Correct Output (Python)

```py
def sample_delete_company(project_id_changed, company_id_changed):
    """Delete Company"""

    # [START talent_delete_company_core]

    client = talent_v4beta1.CompanyServiceClient()

    # project_id_changed = 'Your Google Cloud Project ID CHANGED'
    # company_id_changed = 'ID of the company to delete'

    if isinstance(project_id_changed, six.binary_type):
        project_id_changed = project_id_changed.decode('utf-8')
    if isinstance(company_id_changed, six.binary_type):
        company_id_changed = company_id_changed.decode('utf-8')
    name = client.company_path(project_id_changed, company_id_changed)

    client.delete_company(name)
    # What is going on?
    print('Hello???')
    print('Deleted company')
```

#### Incorrect Output (Node.js - response handling missing)

```js
const talent = require('@google-cloud/talent').v4beta1;

function sampleDeleteCompany(projectIdChanged, companyIdChanged) {
  const client = new talent.CompanyServiceClient();
  // const projectIdChanged = 'Your Google Cloud Project ID CHANGED';
  // const companyIdChanged = 'ID of the company to delete';
  const formattedName = client.companyPath(projectIdChanged, companyIdChanged);
  client.deleteCompany({name: formattedName}).catch(err => {
    console.error(err);
  });
}
```

/cc @googleapis/samplegen @hzyi-google
