### ISSUE TITLE
SampleGen: can't use field%resource on request field

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2621]
I'm not sure if this is something which can be fixed in my GAPIC configuration or if it's a sample generator issue.

I want to create a Job. Jobs have companies. Here's what I'm trying to call...

 - [`job.proto`](https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job.proto)
 - [`job_service.proto`](https://github.com/googleapis/googleapis/blob/master/google/cloud/talent/v4beta1/job_service.proto)
 - [`talent_gapic.yaml`](https://github.com/beccasaurus/gapic-docs-samples/blob/ee0e6ae1812d1b29ca1049323efc13a6af92eeb3/google/cloud/talent/v4beta1/talent_gapic.yaml#L541-L549)

```proto
rpc CreateJob(CreateJobRequest) returns (Job) {
    option (google.api.http) = {
      post: "/v4beta1/{parent=projects/*}/jobs"
      body: "*"
    };
}

message CreateJobRequest {
  string parent = 1;
  Job job = 2;
}

message Job {
  // Required.
  //
  // The resource name of the company listing the job, such as
  // "projects/api-test-project/companies/foo".
  string company_name = 2;
}
```

```yaml
methods:
- name: CreateJob
  sample_value_sets:
  - id: talent_create_job
    description: Create Job
    parameters:
      defaults:
      - parent%project="Your Google Cloud Project ID"

      # Setting this as a regular string field works OK
      #- job.company_name="Company name, e.g. projects/your-project/companies/company-id"

      # If I try to set the sub-parts of `job.company_name`using % I get this error:
      # java.lang.IllegalArgumentException: The field name is not found in the collection map.
      - job.company_name%project="Your Google Cloud Project ID"
      - job.company_name%company="Company ID"
```

```yaml
collections:
- name_pattern: projects/{project}
  entity_name: project
  language_overrides:
  - language: csharp
    common_resource_name: Google.Api.Gax.ResourceNames.ProjectName
- name_pattern: projects/{project}/companies/{company}
  entity_name: company
- name_pattern: projects/{project}/jobs/{jobs}
  entity_name: job
- name_pattern: projects/{project}/tenants/{tenant}/profiles/{profile}
  entity_name: profile
- name_pattern: projects/{project}/tenants/{tenant}
  entity_name: tenant
```

Given these collections, should setting `- job.company_name%project="Xxx"` work?

@googleapis/samplegen
