### ISSUE TITLE
Allow access to request message via $req in on_success of samples

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2759]
Some APIs return Empty

This means, in the `on_success` we have no variables available to print, we can only print literal strings.

```yaml
on_success:
- print: ["Deleted Dog."]
```

But we often, in hand-written samples, print out the "name"* of what was deleted

```yaml
# method name: DeleteDog

parameters:
  attributes:
  - parameter: name
    sample_argument_name: name

on_success:
- print:
  - "Deleted dog %s"
  - $req.name
```

> \* "name" is often the full path identifier of resources in Google APIs

### Issue

So, actually. Our samples usually pass in path parts. So the above isn't realistic.

This is what we would actually do:

```yaml
# method name: DeleteDog

parameters:
  attributes:
  - parameter: name%project
    sample_argument_name: project_id
  - parameter: name%dog
    sample_argument_name: dog_id

on_success:
- print:
  - "Deleted dog %s"
  - $req.name   # <-- name is composed. the sample uses helper method to build full path.
```

@hzyi-google for your consideration (v1.2)

/cc @munkhuushmgl @googleapis/samplegen
