### ISSUE TITLE
SampleGen: Configure google.protobuf.Timestamp request field

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2762]
```
java.lang.IllegalArgumentException:
Tried to assign value for unsupported type google.protobuf.Timestamp;
```

We should support the following features:
 - **`P0`** allow a Timestamp to be set to the current time `now()`  
  but not allow it to be configured as a method/CLI parameter
 - **`P1`** allow passing a string representation of the Timestamp in JSON format
  See: [JSON Mapping](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto#L99)

```yaml
parameters:
  defaults:
  - timestamp_one=now()
  - timestamp_two="2017-01-15T01:30:15.01Z"
  attributes:
  - parameter: timestamp_one
    description: A timestamp field (defaults to current time)
  - parameter: timestamp_two
    description: |
      A timestamp field, defaults to 1/15/2017
      Can be provided as method param or CLI argument
    sample_argument_name: timestamp_two
```

/cc @googleapis/samplegen
