### ISSUE TITLE
Parameter is not captured inside of the method

### ISSUE THREAD

**Issue by munkhuushmgl** [googleapis/gapic-generator#2773]
My yaml code for iot_send_command sample
https://github.com/googleapis/googleapis/blob/master/google/cloud/iot/v1/device_manager.proto#L506
```yaml
  - name: SendCommandToDevice
    flattening:
      groups:
      - parameters:
        - name
        - binary_data
        - subfolder
    required_fields:
    - name
    - binary_data
    header_request_params:
    - name
    retry_codes_name: rate_limited_aware
    retry_params_name: rate_limited_aware
    field_name_patterns:
      name: device
    resource_name_treatment: STATIC_TYPES
    timeout_millis: 60000
    samples:
      standalone:
      - region_tag: iot_send_command
        value_sets: [iot_send_command]
    sample_value_sets:
    - id: iot_send_command
      description: Send a command to a device.
      parameters:
        defaults:
        - name%device="my-device"
        - name%project="[Google Cloud Project ID]"
        - name%location="us-central1"
        - name%registry="[DeviceRegistry ID]"
        - name%binary_data.encoding=LINEAR16
        attributes:
        - parameter: name%device
          sample_argument_name: deviceId
          description: Device ID
        - parameter: name%project
          sample_argument_name: project_id
          description: Your Google Cloud Project ID
        - parameter: name%location
          sample_argument_name: location
          description: Location, e.g. us-central1
        - parameter: name%registry
          sample_argument_name: registry_id
          description: Device Registry ID
        - parameter: name%data
          sample_argument_name: data
          description: The command data to send to the device.
        - parameter: name%binary_data
          sample_argument_name: data2
          description: The command data to send to the device.
```

screenshot of java code generated
@
![image](https://user-images.githubusercontent.com/45373284/57893566-5731ff80-77f8-11e9-951a-28bb7a27ac62.png)

**Comment by eoogbe** [comment]
Thank you for filing this issue! Can you provide a little more information on what the expected outcome is?

**Comment by munkhuushmgl** [comment]
this is old sample I would like to convert using synthool https://github.com/GoogleCloudPlatform/java-docs-samples/blob/d50c7d4636fabb0fb13166a4d8caf8556df4f5aa/iot/api-client/manager/src/main/java/com/example/cloud/iot/examples/DeviceRegistryExample.java#L784-L806

, From the parameter named data, I assume that string data should have went into ByteString.copyFromUtf8(data)

**Comment by hzyi-google** [comment]
Hi Mike,

Note there's a tiny issue in your yaml:

```yaml
- parameter: name%binary_data
  sample_argument_name: data2
  description: The command data to send to the device.
```

It should have been:
```yaml
- parameter: binary_data <-- binary data is a subfield of the request object, not `name`
  sample_argument_name: data2
  description: The command data to send to the device.
```
