### ISSUE TITLE
Java Snippet Generation Code Style Changes

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2789]
The java samples have a new style guide for snippets, canonical samples can be found at https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/dlp/src/main/java/dlp/snippets

To note some of the things:

- Region Tags should be under the `package` and include `import` statements. (Region tags include almost the whole file
- No need to add a comment to include `imports`
- No longer needed to include java-docs for params, since we now include suggested defaults
- parameter defaults should still include the `type`
  - Example: `public static void sampleAnnotateVideo(String filePath) {`
  - Current: `// filePath = "./resources/cat.mp4";`
  - Should be: `// String filePath = "./resources/cat.mp4";`
- We no longer include `main()` methods

@googleapis/samplegen

**Comment by hzyi-google** [comment]
> No longer needed to include java-docs for params, since we now include suggested defaults

Only the descriptions of those fields without a default value will go up into the Javadoc. One way if to not add any `description` directives for those `attributes` without `sample_argument_name`. For example:

```yaml
- parameters:
  - defaults:
    ...
  - attributes:
       - parameter: file_path
         sample_argument_name: file_path
         description: this description will go right above the default line
       - parameter: some_other_argument
         description: this description will go to javadoc.
``` 

> parameter defaults should still include the `type`

We originally have types in the default lines. Later, we want users to have the experience that when they uncomment the default line, they can run the sample with the default value. To make that happen, we have to remove the type definition in the default lines.
