### ISSUE TITLE
Dialogflow Sample gen

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2790]
@googleapis/samplegen 

When trying to generate Dialogflow samples, came across a few issues.

1. Incorrect import statement in `python` since dialogflow isn't a google.cloud package
- Given: `from google.cloud import dialogflow_v2`
- Correct: `import dialogflow_v2`

2. When trying to set defaults. The generator is too smart. 
yaml code:
```
parameters:
        defaults:
        - parent="projects/PROJECT_ID/agent/sessions/SESSION_ID"
```
Generated Python:
```
parser.add_argument('--session_name', type=str, default=client.session_path('[PROJECT]', '[SESSION]'))
```

But the problem is that the `client` has not yet been defined.

**Comment by hzyi-google** [comment]
@nnegrey 

Thanks for letting us know.

> 1. Incorrect import statement in python since dialogflow isn't a google.cloud package

This can't be done by the generator, but I got confirmed that this can be done via synth. cc/ @beccasaurus 

> 2. When trying to set defaults. The generator is too smart.

For now we don't support configuring the entire resource name - we only support configuring fields of the resource names. For example, you can do:

```
parameters:
  - defaults:
      parent.project_id = PROJECT_ID
      parent.session_id = SESSION_ID
```

**Comment by beccasaurus** [comment]
> Incorrect import statement in python since dialogflow isn't a google.cloud package
> This can't be done by the generator, but I got confirmed that this can be done via synth

Correct, [SynthTool](https://github.com/googleapis/synthtool) is the correct tool for this.

The output which GAPIC generates != the API interface that we publish to package managers in some cases.

GAPIC generates the raw library. It is not aware of various concerns. And sometimes does not work without changes (e.g. Ruby)

Using `synth.py` to make replacements in the generates samples is the correct approach 👍 

> defaults:
> - parent="projects/PROJECT_ID/agent/sessions/SESSION_ID"

For `parent` and `name` fields, which are resource paths, you should do the following:

```yaml
 - id: my_sample
    parameters:
      defaults:
      - parent%project="Your Google Cloud Project ID"
      - parent%session="Session ID"
      attributes:
      - parameter: parent%project
         sample_argument_name: project_id
         description: "Your Google Cloud Project ID"
      - parameter: parent%session
         sample_argument_name: session_id
         description: "Session ID"
```

This will add CLI arguments to provide Project ID and Session ID separately. The generated code will not simply concatenate these together, it will use the canonical language approach for building resource paths (in most languages, it calls a helper method for building a path string or object).

We cannot provide a default value for `project` because it needs to be the actual user's project ID, which they can pass via `--project_id`

#### Where do %project and %session come from?

You can find the names for these under `collections:` in the GAPIC config.

e.g. you can find this in the [`dialogflow_gapic.yaml`](https://github.com/googleapis/googleapis/blob/master/google/cloud/dialogflow/v2/dialogflow_gapic.yaml#L225-L227)

```yaml
  collections:
  - name_pattern: projects/{project}/agent/sessions/{session}
    entity_name: session
  - name_pattern: projects/{project}/agent/sessions/{session}/contexts/{context}
    entity_name: context
```
