### ISSUE TITLE
SampleGen Request: re-use variables (e.g. to fix project, project_2, project_3 variables)

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2797]
@googleapis/samplegen 

In some instances, we have to define `Project_ID` (or other parameters) in multiple places.

It would be nice to be able to do some form of the below and reuse a parameter value in multiple places. 
```
defaults:
  - parent%project="[Google Cloud Project ID]"
  - context.name%project="[Google Cloud Project ID]"
  attributes:
   - parameter: parent%project, context.name%project
     description: "Your Google Cloud Project ID"
     sample_argument_name: project_id
```
or some form of default variable reuse.
```
defaults:
  - parent%project="[Google Cloud Project ID]"
  - context.name%project=parent%project
```
