### ISSUE TITLE
SampleGen Collections not overwriteable

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2803]
@googleapis/samplegen 

When trying to use a collection to generate code. The `entity_type` value is using some default and not the value I specified. But the `project` field does use mine. 

Possible issue location: 
```
collections:
  - name_pattern: projects/{project}/agent/entityTypes/{entity_type}
    entity_name: entity_type
field_name_patterns:
      name: entity_type
```

Yaml Code:
```
    samples:
      standalone:
      - region_tag: dialogflow_delete_entity_type
        value_sets: [dialogflow_delete_entity_type]
    sample_value_sets:
    - id: dialogflow_delete_entity_type
      description: "Deletes the specified entity type."
      parameters:
        defaults:
        - name%project="[Google Cloud Project ID] TEST"
        - name%entity="[MY CUSTOM ENTITY VALUE]"
      on_success:
      - print: [Operation Completed]
```
Generated: 
Where the line `client.entity_type_path('[Google Cloud Project ID] TEST', '[ENTITY_TYPE]')`
Uses `ENITITY_TYPE` rather than `[MY CUSTOM ENTITY VALUE]`
```
  client = dialogflow_v2.EntityTypesClient()

  name = client.entity_type_path('[Google Cloud Project ID] TEST', '[ENTITY_TYPE]')

  client.delete_entity_type(name)
  print('Operation Completed')
```

**Comment by hzyi-google** [comment]
Seems to be related to #2719. I'll investigate.

**Comment by hzyi-google** [comment]
Ah I see the issue here.

```yaml
 parameters:
      defaults:
        - name%project="[Google Cloud Project ID] TEST"
        - name%entity="[MY CUSTOM ENTITY VALUE]" # <--- this should have been `name%entity_type`
```

Basically, the field that follows the `%` should be one of the `{curly braced}` components in `name_pattern`,  and their texts should match exactly.

The generator should have throw an error rather than pick a default value in this case.
