### ISSUE TITLE
Access resource name entities in the response handling

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator#2804]
We should be able to do:

```yaml
- print:
  - "this is the project id: %s"
  - $resp.project_name%project_id
```

cc/ @googleapis/samplegen
