### ISSUE TITLE
SampleGen: Can't generate floats for Java.

### ISSUE THREAD

**Issue by nnegrey** [googleapis/gapic-generator#2814]
@googleapis/samplegen 

Tried to generate samples in Java.

In yaml parameters defaults.
```
- config.speech_contexts[0].boost=20.0
```
Generates:
```
$unhandledCase: float$
```

Complete yaml:
```
- id: speech_adaptation_beta
      description: "Performs synchronous speech recognition with speech adaptation."
      parameters:
        defaults:
        - config.encoding=MP3
        - config.sample_rate_hertz=44100
        - config.language_code="en-US"
        - config.speech_contexts[0].phrases[0]="Brooklyn Bridge"
        - config.speech_contexts[0].boost=20.0
        - audio.uri="gs://cloud-samples-data/speech/brooklyn_bridge.mp3"
        attributes:
        - parameter: config.sample_rate_hertz
          sample_argument_name: sample_rate_hertz
          description: "Sample rate in Hertz of the audio data sent in all `RecognitionAudio` messages. Valid values are: 8000-48000."
        - parameter: config.language_code
          sample_argument_name: language_code
          description: The language of the supplied audio.
        - parameter: config.speech_contexts[0].phrases[0]
          sample_argument_name: phrase
          description: Phrase "hints" help Speech-to-Text API recognize the specified phrases from your audio data.
        - parameter: config.speech_contexts[0].boost
          sample_argument_name: boost
          description: Positive value will increase the probability that a specific phrase will be recognized over other similar sounding phrases.
        - parameter: audio.uri
          sample_argument_name: uri_path
          description: Path to the audio file stored on GCS.
      on_success:
      - loop:
          variable: result
          collection: "$resp.results"
          body:
          - comment:
            - First alternative is the most probable result
          - define: alternative=result.alternatives[0]
          - print:
            - 'Transcript: %s'
```

Relevant Java Snippet **Code**
```
public static void main(String[] args) throws Exception {
    Options options = new Options();
    options.addOption(
        Option.builder("")
          .required(false)
          .hasArg(true)
          .longOpt("sample_rate_hertz")
          .build());
    options.addOption(
        Option.builder("")
          .required(false)
          .hasArg(true)
          .longOpt("language_code")
          .build());
    options.addOption(
        Option.builder("")
          .required(false)
          .hasArg(true)
          .longOpt("phrase")
          .build());
    options.addOption(
        Option.builder("")
          .required(false)
          .hasArg(true)
          .longOpt("boost")
          .build());
    options.addOption(
        Option.builder("")
          .required(false)
          .hasArg(true)
          .longOpt("uri_path")
          .build());

    CommandLine cl = (new DefaultParser()).parse(options, args);
    int sampleRateHertz =
        cl.getOptionValue("sample_rate_hertz") != null
            ? Integer.parseInt(cl.getOptionValue("sample_rate_hertz"))
            : 44100;
    String languageCode = cl.getOptionValue("language_code", "en-US");
    String phrase = cl.getOptionValue("phrase", "Brooklyn Bridge");
    $unhandledCase: float$
    String uriPath = cl.getOptionValue("uri_path", "gs://cloud-samples-data/speech/brooklyn_bridge.mp3");

    sampleRecognize(sampleRateHertz, languageCode, phrase, boost, uriPath);
  }
```
