### ISSUE TITLE
SampleGen: options to not wait for LRO & to stop operation

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2838]
Some LROs may take hours to complete.

To run samples, we have often handled this in one of two ways:
 1. The sample shows the code to run the LRO and then shows the code to **stop the operation** with a comment mentioning what we're doing (users at home can copy/paste and they have the code to stop the operation if they need to)
 2. The sample **does not block** / wait for the LRO to complete. We run the sample (which prints out its operation ID) and then cancel the operation via an API call after the same runs.

Request: **Non-Blocking** version of LRO calls

```yaml
service: SomeThing
rpc: LongRunningRecognize
lro: blocking
# ...
lro: non_blocking
# ...
# or
# ...
lro: instant
lro: do_not_wait
```
... or something 🤷🏼‍♀️

Supporting Blocking & Non Blocking is a reasonable, necessary use-case.

For monolith implementation, it could internally choose the correct calling forms.
They may already be available?

@googleapis/samplegen 

----

#misc
This is another blocker for AutoML.
Also a blocker for Data Labeling.
