### ISSUE TITLE
SampleGen: sample metadata usage rendering wrong with "[String Values in Brackets]"

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2961]
### Steps to Reproduce
 - Set the value of any input_parameter to a string wrapped in brackets  
   > e.g. `value: "[Google Cloud Project ID]"`
 - Generate code samples (tested with Python)

### Expected Result
 - Usage metadata should look like this:  
   ```yaml
   usage: python3 samples/v3beta1/translate_foo.py [--project "[Google Cloud Project ID]"]
   ```

### Actual Result
 - The first bracket is missing!!  
   ```yaml
   usage: python3 samples/v3beta1/translate_foo.py [--project "Google Cloud Project ID]"]
   ```

I have tools which treat [bracket wrapped] values in a special way (I've been using this as a convention for required values)

@googleapis/samplegen 

----

Here's a Translation v3beta1 code sample for repro:

```yaml
type: com.google.api.codegen.samplegen.v1p2.SampleConfigProto
schema_version: 1.2.0
samples:
- region_tag: translate_list_language_names_beta
  title: List Supported Language Names and Codes
  description: Listing supported languages with target language name
  service: google.cloud.translation.v3beta1.TranslationService
  rpc: GetSupportedLanguages
  request:
  - field: display_language_code
    value: en
    comment: |
      The language to use to return localized, human readable names of supported languages.
    input_parameter: language_code
  - field: parent%project
    value: "[Google Cloud Project ID]"
    input_parameter: project
  - field: parent%location
    value: global
  response:
  - comment:
    - List language codes of supported languages
  - loop:
      collection: "$resp.languages"
      variable: language
      body:
      - print:
        - "Language Code: %s"
        - language.language_code
      - print:
        - "Display Name: %s"
        - language.display_name
```
