### ISSUE TITLE
SampleGen: can't find field on request object? [TranslationService.CreateGlossary]

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2963]
I can no longer generate the sample below.

Error message:
```
ERROR: toplevel: Unexpected exception:

java.lang.IllegalArgumentException:
The field name is not found in the collection map.
Field name: glossary.name, map keys: [parent]
```

I'm calling:
```yaml
service: google.cloud.translation.v3beta1.TranslationService
rpc: CreateGlossary
```

![Screen Shot 2019-08-30 at 7 28 43 PM](https://user-images.githubusercontent.com/280/64058190-6432ee80-cb5c-11e9-88d6-a17c42c24b7b.png)

This Request requires that 2 fields be set: `parent` and `glossary`

The Error message seems to imply that it's only seeing the `parent` field and not the `glossary` field (the object to create)

----

Full YAML below:
```yaml
type: com.google.api.codegen.samplegen.v1p2.SampleConfigProto
schema_version: 1.2.0
samples:
- region_tag: translate_create_glossary_beta
  title: Create Glossary
  description: Create Glossary
  service: google.cloud.translation.v3beta1.TranslationService
  rpc: CreateGlossary
  request:
  # Configure parent (Google Cloud Project + Location to scope this Glossary under)
  - field: parent%project
    value: "[Google Cloud Project ID]"
    input_parameter: project
  - field: parent%location
    value: us-central1

  # Pass full resource name for Glossary resource to create (?)
  #
  # Google Cloud APIs aren't supposed to have you provide the #name of objects on create,
  # instead Glosary should have a display_name and the ID should be server-side generated.
  # See: https://aip.dev/133#user-specified-ids
  #
  # Nevertheless, the Translation v3beta1 API currently requires you to pass the full
  # glossary name on create or else you get this API error:
  # > "Empty resource name.;  Resource type: glossary"
  #
  - field: glossary.name%project
    value: "[Your Google Cloud Project ID]"
    input_parameter: project_2

  - field: glossary.name%location
    value: us-central1

  - field: glossary.name%glossary
    value: my_glossary_id_123
    input_parameter: glossary_id

  # Glossary configuration
  - field: glossary.language_codes_set.language_codes[0]
    value: en
  - field: glossary.language_codes_set.language_codes[1]
    value: es
  - field: glossary.input_config.gcs_source.input_uri
    value: gs://cloud-samples-data/translation/glossary.csv
  response:
  - print:
    - Created Glossary.
  - print:
    - 'Glossary name: %s'
    - "$resp.name"
  - print:
    - 'Entry count: %s'
    - "$resp.entry_count"
  - print:
    - 'Input URI: %s'
    - "$resp.input_config.gcs_source.input_uri"
```

@googleapis/samplegen

**Comment by beccasaurus** [comment]
Note: the `glossary.name` `project/location/glossary` come from the defined collections:
```yaml
  collections:
  - name_pattern: projects/{project}/locations/{location}
    entity_name: location
  - name_pattern: projects/{project}/locations/{location}/glossaries/{glossary}
    entity_name: glossary
```

This sample used to generate as-is for me afaicr 😕
