### ISSUE TITLE
gapic-generator can not generate without empty collections list.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#2971]
This GAPIC config v2 is able to generate a Java GAPIC:

```yaml
type: com.google.api.codegen.ConfigProto
config_schema_version: 2.0.0
# The settings of generated code in a specific language.
language_settings:
  java:
    package_name: com.google.cloud.texttospeech.v1
  python:
    package_name: google.cloud.texttospeech_v1.gapic
  go:
    package_name: cloud.google.com/go/texttospeech/apiv1
  csharp:
    package_name: Google.Cloud.TextToSpeech.V1
  ruby:
    package_name: Google::Cloud::TextToSpeech::V1
  php:
    package_name: Google\Cloud\TextToSpeech\V1
  nodejs:
    package_name: text-to-speech.v1
    domain_layer_location: google-cloud
interfaces:
  # The fully qualified name of the API interface.
  - name: google.cloud.texttospeech.v1.TextToSpeech
    collections: []
```

However, if the last four lines are removed (as they should be), generation crashes with:

```
ERROR: toplevel: Unexpected exception:
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4456)
	at com.google.api.codegen.ConfigProto.getInterfaces(ConfigProto.java:432)
	at com.google.api.codegen.config.GapicProductConfig.create(GapicProductConfig.java:191)
	at com.google.api.codegen.gapic.GapicGeneratorApp.process(GapicGeneratorApp.java:212)
	at com.google.api.tools.framework.tools.GenericToolDriverBase.run(GenericToolDriverBase.java:90)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:73)
	at com.google.api.codegen.GeneratorMain.gapicGeneratorMain(GeneratorMain.java:338)
	at com.google.api.codegen.GeneratorMain.main(GeneratorMain.java:190)
```

**Comment by eoogbe** [comment]
This is as intended. Delete the collections field if it is empty.

**Comment by hzyi-google** [comment]
Okay some progress.

@lukesneeringer Please add a `proto_package` in artman config if you delete all the interfaces (per: https://github.com/googleapis/artman/pull/636)

But that is causing another issue in generating Java `package-info.java` file, which I am still investigating.

**Comment by hzyi-google** [comment]
Whoops that was me adding the wrong proto package.
For this case, please update artman yaml this way:

```
common:
  api_name: texttospeech
  api_version: v1
  organization_name: google-cloud
  proto_deps:
    - name: google-common-protos
  src_proto_paths:
  - v1
  service_yaml: tts_v1.yaml
  gapic_yaml: v1/texttospeech_gapic.yaml
  proto_package: google.cloud.texttospeech.v1
```

My understanding on why this is needed:

gapic-generator needs this information to find `service`s we need to generate gapic for. When we were using gapic config, we generate clients for all services with a corresponding interface config. But when we remove the gapic config (or remove all the interface configs from gapic config), gapic generator does not know which services to generate clients for. Adding a `proto_package` in artman config will tell gapic-generator to generate clients for all `service`s in this package.

I am closing it here, since there is no work to be done in gapic-generator.
