### ISSUE TITLE
gapic-generator does not understand projects

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator#2972]
Many GCP APIs have the (shared) concept of a _project_, which is at the top of the hierarchy for most GCP resources.

Accordingly, the GAPIC config often has a block that looks like this:

```yaml
  collections:
  - entity_name: project
    language_overrides:
    - language: csharp
      common_resource_name: Google.Api.Gax.ResourceNames.ProjectName
```

Generating C# with this block crashes with the error described here: https://github.com/googleapis/google-cloud-dotnet/issues/3423

Generating C# with this block removed (which would be a problem for them; the override matters) crashes with a different error:

```
ERROR: toplevel: Reference to unknown type "cloudresourcemanager.googleapis.com/Project" on field google.cloud.phishingprotection.v1beta1.ReportPhishingRequest.google.cloud.phishingprotection.v1beta1.ReportPhishingRequest.parent
```

**P0:** We _either_ need generating with this YAML block to work correctly in all languages, _or_ we need to be able to remove the block completely and have the generator do the correct thing whenever it encounters a project (if choosing between them, removal is better,  but the P0 is to get this working)...

**P1:** ...or org, folder, or billing account.
