### ISSUE TITLE
YAML parser breaks when using Merge Key <<

### ISSUE THREAD

**Issue by beccasaurus** [googleapis/gapic-generator#2988]
> `<<: *map` :: https://yaml.org/type/merge.html

When **writing samples**, YAML gives the benefit of using `&anchors` and `*aliases` [`^`](https://yaml.org/spec/1.1/#id863390)

I can't get key merging to work, however.

```
Found field '<<' which is unknown
```

Example:
```yaml
samples:

- region_tag: sample_one
  request:
  - &encoding_field
    field: config.encoding
    value: UTF8
    comment: Encoding of the thingy

# ERROR!
# Found field '<<' which is unknown in 'com.google.api.codegen.samplegen.v1p2.RequestFieldProto'
- region_tag: sample_two
  request:
  - << : *encoding_field 
    value: UTF16

# This works, but it takes the full map, it does not merge.
# This means you can either have the whole object or none of it. Doesn't work. 😔
- region_tag: sample_three
  request:
  - *encoding_field
    # value: doesn't work here
```
